-- ============================================================
-- Migration: 008_create_signals_tables.sql
-- Description: Trading signals and their tracked performance
-- Platform: PostgreSQL 15+
-- ============================================================

-- ------------------------------------------------------------
-- Enum: signal_type
-- ------------------------------------------------------------
CREATE TYPE signal_type AS ENUM ('BUY', 'SELL', 'HOLD');

-- ------------------------------------------------------------
-- Enum: signal_strength
-- ------------------------------------------------------------
CREATE TYPE signal_strength AS ENUM ('weak', 'moderate', 'strong', 'very_strong');

-- ------------------------------------------------------------
-- Enum: signal_timeframe
-- ------------------------------------------------------------
CREATE TYPE signal_timeframe AS ENUM (
    'intraday',
    'short_term',
    'medium_term',
    'long_term'
);

-- ------------------------------------------------------------
-- Enum: signal_status
-- ------------------------------------------------------------
CREATE TYPE signal_status AS ENUM (
    'pending',
    'active',
    'triggered',
    'expired',
    'cancelled'
);

-- ------------------------------------------------------------
-- Enum: signal_outcome
-- ------------------------------------------------------------
CREATE TYPE signal_outcome AS ENUM ('win', 'loss', 'breakeven', 'expired');

-- ------------------------------------------------------------
-- Table: signals
-- Algorithmic and analyst-generated trading signals
-- ------------------------------------------------------------
CREATE TABLE signals (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    asset_id                UUID NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    generated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    signal_type             signal_type NOT NULL,
    strength                signal_strength NOT NULL,
    timeframe               signal_timeframe NOT NULL,

    -- Pricing targets
    entry_price             NUMERIC(18, 6),
    target_price_1          NUMERIC(18, 6),
    target_price_2          NUMERIC(18, 6),
    stop_loss               NUMERIC(18, 6),
    risk_reward_ratio       NUMERIC(8, 4),

    -- Confidence & probability
    probability_success     NUMERIC(6, 2),             -- 0.00 to 100.00
    confidence_score        NUMERIC(6, 2),             -- 0.00 to 100.00

    -- Component scores
    technical_score         NUMERIC(6, 2),
    fundamental_score       NUMERIC(6, 2),
    sentiment_score         NUMERIC(6, 2),
    macro_score             NUMERIC(6, 2),
    composite_score         NUMERIC(6, 2),

    -- Narrative
    reasoning               TEXT,
    key_factors             JSONB NOT NULL DEFAULT '[]',   -- positive factors driving the signal
    risk_factors            JSONB NOT NULL DEFAULT '[]',   -- identified risks

    -- Lifecycle
    expires_at              TIMESTAMPTZ,
    is_active               BOOLEAN NOT NULL DEFAULT TRUE,
    status                  signal_status NOT NULL DEFAULT 'pending',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Score validations
    CONSTRAINT sig_probability_range    CHECK (
        probability_success IS NULL OR
        (probability_success >= 0 AND probability_success <= 100)
    ),
    CONSTRAINT sig_confidence_range     CHECK (
        confidence_score IS NULL OR
        (confidence_score >= 0 AND confidence_score <= 100)
    ),
    CONSTRAINT sig_tech_score_range     CHECK (technical_score IS NULL OR (technical_score >= 0 AND technical_score <= 100)),
    CONSTRAINT sig_fund_score_range     CHECK (fundamental_score IS NULL OR (fundamental_score >= 0 AND fundamental_score <= 100)),
    CONSTRAINT sig_sent_score_range     CHECK (sentiment_score IS NULL OR (sentiment_score >= 0 AND sentiment_score <= 100)),
    CONSTRAINT sig_macro_score_range    CHECK (macro_score IS NULL OR (macro_score >= 0 AND macro_score <= 100)),
    CONSTRAINT sig_comp_score_range     CHECK (composite_score IS NULL OR (composite_score >= 0 AND composite_score <= 100)),
    CONSTRAINT sig_rr_positive          CHECK (risk_reward_ratio IS NULL OR risk_reward_ratio > 0),
    CONSTRAINT sig_entry_positive       CHECK (entry_price IS NULL OR entry_price > 0)
);

COMMENT ON TABLE  signals                       IS 'Trading signals generated by algorithms or analysts with multi-factor scoring';
COMMENT ON COLUMN signals.risk_reward_ratio     IS 'Potential reward / potential risk; higher is more favorable';
COMMENT ON COLUMN signals.probability_success   IS 'Estimated probability (0-100) that the signal reaches target_price_1';
COMMENT ON COLUMN signals.confidence_score      IS 'Overall model confidence (0-100) in the signal quality';
COMMENT ON COLUMN signals.composite_score       IS 'Weighted blend of technical, fundamental, sentiment, and macro scores';
COMMENT ON COLUMN signals.key_factors           IS 'JSON array of bullish/bearish factors supporting the signal';
COMMENT ON COLUMN signals.risk_factors          IS 'JSON array of identified risks that could invalidate the signal';

CREATE INDEX idx_sig_asset_id       ON signals (asset_id);
CREATE INDEX idx_sig_generated_at   ON signals (asset_id, generated_at DESC);
CREATE INDEX idx_sig_signal_type    ON signals (signal_type);
CREATE INDEX idx_sig_active         ON signals (is_active, status) WHERE is_active = TRUE;
CREATE INDEX idx_sig_status         ON signals (status, generated_at DESC);
CREATE INDEX idx_sig_timeframe      ON signals (timeframe, generated_at DESC);
CREATE INDEX idx_sig_composite      ON signals (composite_score DESC);
CREATE INDEX idx_sig_expires_at     ON signals (expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_sig_key_factors    ON signals USING GIN (key_factors);
CREATE INDEX idx_sig_risk_factors   ON signals USING GIN (risk_factors);

-- ------------------------------------------------------------
-- Table: signal_performance
-- Post-hoc performance tracking for closed signals
-- ------------------------------------------------------------
CREATE TABLE signal_performance (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    signal_id               UUID NOT NULL REFERENCES signals (id) ON DELETE CASCADE,
    triggered_at            TIMESTAMPTZ,                -- when entry_price was hit
    closed_at               TIMESTAMPTZ,                -- when position was closed (target or stop)
    actual_return_percent   NUMERIC(10, 4),             -- realized return %
    max_drawdown_percent    NUMERIC(10, 4),             -- worst intraperiod drawdown %
    days_held               INTEGER,
    outcome                 signal_outcome,
    notes                   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT sp_signal_id_unique      UNIQUE (signal_id),
    CONSTRAINT sp_days_held_positive    CHECK (days_held IS NULL OR days_held >= 0),
    CONSTRAINT sp_drawdown_range        CHECK (
        max_drawdown_percent IS NULL OR
        (max_drawdown_percent >= -100 AND max_drawdown_percent <= 0)
    )
);

COMMENT ON TABLE  signal_performance                        IS 'Tracks realized performance of signals after they are closed';
COMMENT ON COLUMN signal_performance.triggered_at           IS 'Timestamp when price reached the signal entry_price';
COMMENT ON COLUMN signal_performance.actual_return_percent  IS 'Realized P&L percentage from entry to close';
COMMENT ON COLUMN signal_performance.max_drawdown_percent   IS 'Maximum adverse price movement while in the trade (negative value)';
COMMENT ON COLUMN signal_performance.outcome                IS 'win (hit target_price_1), loss (hit stop_loss), breakeven, expired';

CREATE INDEX idx_sp_signal_id   ON signal_performance (signal_id);
CREATE INDEX idx_sp_outcome     ON signal_performance (outcome);
CREATE INDEX idx_sp_closed_at   ON signal_performance (closed_at DESC);
